# Generated by Django 2.0 on 2018-04-01 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20180401_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='course',
            name='user',
        ),
    ]
