# Generated by Django 2.0 on 2018-04-06 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank='Select Teacher', default=True, on_delete=django.db.models.deletion.CASCADE, related_name='teahcers', to='courses.Teacher'),
        ),
    ]
