# Generated by Django 2.0 on 2018-04-07 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_auto_20180406_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='step_detail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='courses.Step'),
            preserve_default=False,
        ),
    ]
