# Generated by Django 2.0 on 2018-04-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_auto_20180407_1904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='related_course',
            new_name='course',
        ),
        migrations.AlterField(
            model_name='step',
            name='related_image',
            field=models.ImageField(default='media/default.png', upload_to='Step_Images'),
        ),
    ]
