# Generated by Django 2.0.5 on 2018-06-17 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0032_auto_20180617_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='course',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
