# Generated by Django 2.0 on 2018-06-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0035_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
