# Generated by Django 2.0 on 2018-03-30 16:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20180330_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='title_html',
            field=models.TextField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
    ]
