# Generated by Django 2.0 on 2018-04-05 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20180402_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='title_html',
        ),
    ]
