# Generated by Django 2.0 on 2018-04-05 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_remove_course_title_html'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='created_by',
        ),
    ]
