# Generated by Django 2.0 on 2018-04-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default='media/default.png', upload_to='course_images'),
        ),
    ]
