# Generated by Django 2.0 on 2018-06-28 06:51

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0034_auto_20180628_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Category'),
        ),
    ]
