# Generated by Django 2.0 on 2018-07-02 11:44

from django.db import migrations, models
import geoposition.fields
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0037_auto_20180630_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointOfInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', geoposition.fields.GeopositionField(max_length=42)),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='Description'),
        ),
    ]
