# Generated by Django 2.0 on 2018-07-02 11:56

from django.db import migrations, models
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0038_auto_20180702_1644'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pointofinterest',
            options={'verbose_name_plural': 'points of interest'},
        ),
        migrations.AddField(
            model_name='pointofinterest',
            name='address',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pointofinterest',
            name='city',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pointofinterest',
            name='zipcode',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pointofinterest',
            name='position',
            field=geoposition.fields.GeopositionField(blank=True, max_length=42),
        ),
    ]
